# Generated by Django 3.2.9 on 2021-11-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=8)),
                ('direccion_cliente', models.CharField(max_length=250)),
                ('estado_caso', models.CharField(max_length=60)),
                ('fecha_recibido', models.DateField()),
                ('fecha_entregado', models.DateField()),
                ('monto', models.FloatField(default=0)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelo')),
                ('id_tipo_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocaso')),
                ('id_tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodispositivo')),
            ],
        ),
    ]
